[project]
name = "luo-li-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.12"
dependencies = [
    "langgraph>=1.0.8",
]

[tool.ruff.format]
quote-style = "single"
